---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisionedpartienv-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - parti.io
  resources:
  - provisionedpartienvs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - parti.io
  resources:
  - provisionedpartienvs/status
  verbs:
  - get
  - patch
  - update
