//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplySummary) DeepCopyInto(out *ApplySummary) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplySummary.
func (in *ApplySummary) DeepCopy() *ApplySummary {
	if in == nil {
		return nil
	}
	out := new(ApplySummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpec) DeepCopyInto(out *ControlPlaneSpec) {
	*out = *in
	out.WorkerIDTTL = in.WorkerIDTTL
	out.ElectionTimeout = in.ElectionTimeout
	out.HeartbeatTTL = in.HeartbeatTTL
	out.AssignmentTTL = in.AssignmentTTL
	out.HandoffTTL = in.HandoffTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpec.
func (in *ControlPlaneSpec) DeepCopy() *ControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSAuthSecret) DeepCopyInto(out *NATSAuthSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSAuthSecret.
func (in *NATSAuthSecret) DeepCopy() *NATSAuthSecret {
	if in == nil {
		return nil
	}
	out := new(NATSAuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSConnection) DeepCopyInto(out *NATSConnection) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(NATSAuthSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSConnection.
func (in *NATSConnection) DeepCopy() *NATSConnection {
	if in == nil {
		return nil
	}
	out := new(NATSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionSourceSpec) DeepCopyInto(out *PartitionSourceSpec) {
	*out = *in
	out.TTL = in.TTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionSourceSpec.
func (in *PartitionSourceSpec) DeepCopy() *PartitionSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PartitionSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanSummary) DeepCopyInto(out *PlanSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanSummary.
func (in *PlanSummary) DeepCopy() *PlanSummary {
	if in == nil {
		return nil
	}
	out := new(PlanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedPartiEnv) DeepCopyInto(out *ProvisionedPartiEnv) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedPartiEnv.
func (in *ProvisionedPartiEnv) DeepCopy() *ProvisionedPartiEnv {
	if in == nil {
		return nil
	}
	out := new(ProvisionedPartiEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProvisionedPartiEnv) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedPartiEnvList) DeepCopyInto(out *ProvisionedPartiEnvList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProvisionedPartiEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedPartiEnvList.
func (in *ProvisionedPartiEnvList) DeepCopy() *ProvisionedPartiEnvList {
	if in == nil {
		return nil
	}
	out := new(ProvisionedPartiEnvList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProvisionedPartiEnvList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedPartiEnvSpec) DeepCopyInto(out *ProvisionedPartiEnvSpec) {
	*out = *in
	in.NATS.DeepCopyInto(&out.NATS)
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(ControlPlaneSpec)
		**out = **in
	}
	if in.PartitionSource != nil {
		in, out := &in.PartitionSource, &out.PartitionSource
		*out = new(PartitionSourceSpec)
		**out = **in
	}
	if in.Streams != nil {
		in, out := &in.Streams, &out.Streams
		*out = make([]StreamSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedPartiEnvSpec.
func (in *ProvisionedPartiEnvSpec) DeepCopy() *ProvisionedPartiEnvSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisionedPartiEnvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedPartiEnvStatus) DeepCopyInto(out *ProvisionedPartiEnvStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.LastPlan != nil {
		in, out := &in.LastPlan, &out.LastPlan
		*out = new(PlanSummary)
		**out = **in
	}
	if in.LastApply != nil {
		in, out := &in.LastApply, &out.LastApply
		*out = new(ApplySummary)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedPartiEnvStatus.
func (in *ProvisionedPartiEnvStatus) DeepCopy() *ProvisionedPartiEnvStatus {
	if in == nil {
		return nil
	}
	out := new(ProvisionedPartiEnvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamSpec) DeepCopyInto(out *StreamSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.MaxAge = in.MaxAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamSpec.
func (in *StreamSpec) DeepCopy() *StreamSpec {
	if in == nil {
		return nil
	}
	out := new(StreamSpec)
	in.DeepCopyInto(out)
	return out
}
